name: Auto-Report

on:
  push:
    branches:
      - master
  schedule:
    - cron: '30 4,11,23 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run report script
        env:
          STUID: ${{ secrets.Stuid }}
          PASSWORD: ${{ secrets.Password }}
        run: python report.py data.json "$STUID" "$PASSWORD"
